### ISSUE TITLE
Harpoon Timer for Razorscale is wrong

### ISSUE THREAD

**Issue by whives** [dnzr/DBM-LFR#10]

**Comment by dnzr** [comment]
i fixed some values, the timer after "grounded" phase was completly different from timer of "combatStart". i guess its the same amount of time for the harpoons to be ready. ground phase time was reduced from 45s to 38s. harpoon timer after ground phase starts with emote "Give us a moment to prepare to build the turrets"

**Comment by dnzr** [comment]
timerFuseArmorCD is definitly wrong too. saw FuseArmor used again 5-6sec after being casted. gotta look for rng code in server core scripts. 12.1s is wrong though. and sound "stackhigh" is played after having 2 or more debuffs.. its kinda low? maybe play this sound at 4 stacks or higher idk.
