### ISSUE TITLE
Malygos Breath Timer (ARcane Breath)

### ISSUE THREAD

**Issue by whives** [dnzr/DBM-LFR#9]
case EVENT_ARCANE_BREATH:
                        if (_executingVortex)
                        {
                            events.ScheduleEvent(EVENT_ARCANE_BREATH, 20s, 0, PHASE_ONE);
                            break;
                        }
  
                        me->CastSpell(me->GetVictim(), SPELL_ARCANE_BREATH, true);
                        events.ScheduleEvent(EVENT_ARCANE_BREATH, 20s, 0, PHASE_ONE);
                        break;

Possible, thats 20 seconds timer?

**Comment by dnzr** [comment]
where you got that code from? 
But yes it seems its 20sec Timer Arcane Breath after Malygos casted Vortex or Arcane Breath? Not 100% sure
